### ISSUE TITLE
Failing Travis Build

### ISSUE THREAD

**Issue by themetalone** [maybeec/lexeme#8]
The Travis Build fails but the local builds don't. 

The Problem seems to be that Travis cannot access/parse the merge schemas properly.

**Comment by themetalone** [comment]
The Provider itself doesn't seem to be the cause of the failing tests since the providers unit tests pass

**Comment by maybeec** [comment]
Any chance, that this is just a file access issue of capital vs. non-captial letters? As windows ignores letter case and on linux machines the letter case bothers!
